[[language]]
name = "python"
auto-format = true
language-servers = [
  {name = "ty", except-features = [ "completion", "signature-help" ]},
  "ruff",
  "jedi",
]

[language-server.jedi]
config.workspace.environmentPath = ".venv"


[[language]]
name = "markdown"
language-servers = [ "mpls" ]

[language-server.mpls]
command = "mpls"
config = { markdown.preview.auto = true }
